[package]
name = "egui-widget-shapes"
version = "0.1.0"
authors = ["Rob Ward <rob@resona.nz>"]
edition = "2021"
include = ["LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.82"
repository = "https://github.com/resonanz/egui-widget-shapes"
keywords = ["eframe", "egui", "ui", "widgets"]
description = "An egui widget that that contains several different shapes and shape response sensings."
license = "MIT"
documentation = "https://docs.rs/egui-widget-shapes"

[dependencies]
egui = "0.29.1"
